# =========================================
# Application Configuration
# =========================================

base.url=https://www.alfadock-pack.com


# =========================================
# Browser Configuration
# =========================================

browser=chrome
headless=false
slowmo=500
timeout=30000


# =========================================
# Language Configuration
# =========================================

selectLanguage=English