# =========================================
# Application Configuration
# =========================================

base.url=https://www.alfadock-pack.com

# =========================================
# Browser Configuration
# =========================================

browser=chrome
headless=false
slowmo=500
timeout=30000

# =========================================
# Company Login Credentials
# =========================================

#Ohkuma credentials
ohkuma.username=oaksystem
ohkuma.password=oak123

#NisinoSeikiss credentials
nisino.compusername=nisinoseikiss
nisino.comppassword=eJ3HZWF6

# =========================================
# User Login Credentials
# =========================================

ohkuma.user.username=admin
ohkuma.user.password=service701

nisino.username=admin
nisino.password=admin

# =========================================
# Screenshot Configuration
# =========================================

screenshot.on.failure=true
screenshot.path=test-output/screenshots

# =========================================
# Allure Configuration
# =========================================

allure.results.directory=target/allure-results

selectLanguage=English