# =========================================
# Application Configuration
# =========================================

base.url=https://www.alfadock-pack.com

# =========================================
# Browser Configuration
# =========================================

browser=chrome
headless=false
slowmo=500
timeout=30000

# =========================================
# Company Login Credentials
# =========================================

#Oaksystem credentials
oaksystem.username=oaksystem
oaksystem.password=oak123

#NisinoSeikiss credentials
nisino.compusername=nisinoseikiss
nisino.comppassword=eJ3HZWF6

#Ohkuma credentials
ohkuma.compusername=Ohkuma
ohkuma.comppassword=ohkuma123

# =========================================
# User Login Credentials
# =========================================

oaksystem.user.username=admin
oaksystem.user.password=service701

nisino.username=admin
nisino.password=admin

ohkuma.user.username=admin
ohkuma.user.password=admin


# =========================================
# Screenshot Configuration
# =========================================

screenshot.on.failure=true
screenshot.path=test-output/screenshots

# =========================================
# Allure Configuration
# =========================================

allure.results.directory=target/allure-results

selectLanguage=English