base.url=https://www.alfadock-pack.com/

browser=chrome
headless=true
slowmo=0
timeout=60000

selectLanguage=English

SENDER_EMAIL_ADDRESS=murali@a-tkg.co.in
APP_PASSWORD=jhzwekqcxpijyxwm
RECEIVER_EMAIL_ADDRESS1=murali0940@gmail.com
RECEIVER_EMAIL_ADDRESS2=murali@a-tkg.co.in
RECEIVER_EMAIL_ADDRESS3=muthu@a-tkg.co.in