# =========================================
# Oaksystem Credentials
# =========================================

oaksystem.username=oaksystem
oaksystem.password=oak123


# =========================================
# NisinoSeikiss Credentials
# =========================================

nisino.compusername=nisinoseikiss
nisino.comppassword=eJ3HZWF6


# =========================================
# Ohkuma Credentials
# =========================================

ohkuma.compusername=Ohkuma
ohkuma.comppassword=ohkuma123


# =========================================
# Sanmatsu Credentials
# =========================================

sanmatsu.compusername=sanmatsu
sanmatsu.comppassword=san1972