# =========================================
# Screenshot Configuration
# =========================================

screenshot.on.failure=true
screenshot.path=test-output/screenshots


# =========================================
# Allure Configuration
# =========================================

allure.results.directory=target/allure-results