# =========================================
# Oaksystem User Credentials
# =========================================

oaksystem.user.username=admin
oaksystem.user.password=service701


# =========================================
# Default User Credentials
# =========================================

username=admin
password=admin